### ISSUE TITLE
is NetCore version in roadmap?

### ISSUE THREAD

**Issue by paul-cheung** [ExaVault/evapi-csharp#3]
it's better to have it in my netcore application, So any plan about porting this lib to core version?

**Comment by AmyExaVault** [comment]
Hey, we're using swagger-codegen to automatically generate this library, and right now we don't have any plans to generate another version targeting a different framework. It seems like you might be able to update the project settings file to use netcore? Since we probably won't be changing that file in subsequent updates to our API classes and models, maybe that would work for you.

**Comment by paul-cheung** [comment]
@AmyExaVault  Got, thanks.
